spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SivaRamiReddyModugula/Online-Student-Access-Catalog/configs
  profiles:
    active:
      - native
server:
  port: 8888
